services:
  - type: web
    name: madrasa-management
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npx next start -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
