services:
  - type: web
    name: madrasa-management
    runtime: node
    plan: free
    region: singapore
    autoDeploy: true
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npx next start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./madrasa.db
